### ISSUE TITLE
Unable to run dvector_create.py, file does not start with RIFF id

### ISSUE THREAD

**Issue by chrisspen** [HarryVolek/PyTorch_Speaker_Verification#63]
Running dvector_create.py with default arguments and the TIMIT data throws the exception:

    Traceback (most recent call last):
      File "dvector_create.py", line 94, in <module>
        times, segs = VAD_chunk(2, folder+'/'+file)
      File "PyTorch_Speaker_Verification/VAD_segments.py", line 131, in VAD_chunk
        audio, byte_audio = read_wave(path, hp.data.sr)
      File "PyTorch_Speaker_Verification/VAD_segments.py", line 26, in read_wave
        with contextlib.closing(wave.open(path, 'rb')) as wf:
      File "/usr/lib/python3.7/wave.py", line 510, in open
        return Wave_read(f)
      File "/usr/lib/python3.7/wave.py", line 164, in __init__
        self.initfp(f)
      File "/usr/lib/python3.7/wave.py", line 131, in initfp
        raise Error('file does not start with RIFF id')
    wave.Error: file does not start with RIFF id

**Comment by xiaozhi2015** [comment]
Make a transformation using SPHFile
