### ISSUE TITLE
error in  training

### ISSUE THREAD

**Issue by Jason-1998** [HarryVolek/PyTorch_Speaker_Verification#72]
(torch) [gjj@localhost PyTorch_Speaker_Verification]$ ./train_speech_embedder.py
/data/gjj/PyTorch_Speaker_Verification/hparam.py:11: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for doc in docs:
Traceback (most recent call last):
  File "./train_speech_embedder.py", line 158, in <module>
    train(hp.model.model_path)
  File "./train_speech_embedder.py", line 44, in train
    for batch_id, mel_db_batch in enumerate(train_loader):
  File "/home/gjj/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/gjj/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gjj/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/gjj/PyTorch_Speaker_Verification/data_load.py", line 77, in __getitem__
    utter_index = np.random.randint(0, utters.shape[0], self.utter_num)   # select M utterances per speaker
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken

I met this error in training phrase, but I don't know why.

**Comment by kouohhashi** [comment]
@Jason-1998 
Hi, I have the same issue.
Have you solved the problem?

**Comment by Jason-1998** [comment]
> @Jason-1998
> Hi, I have the same issue.
> Have you solved the problem?

I think it is because of data preparing. If you prepare data unsuccessfully, you will get .npy files with no data, and this will cause the problem we have met.

**Comment by Reckless564** [comment]
> > @Jason-1998
> > Hi, I have the same issue.
> > Have you solved the problem?
> 
> I think it is because of data preparing. If you prepare data unsuccessfully, you will get .npy files with no data, and this will cause the problem we have met.

hello，have you solve the problem?  I also have get .npy files with no data and dont know how to handle it
